# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_helloextendr_wrappers", use_symbols = TRUE, package_name = "helloextendr")

#' @docType package
#' @usage NULL
#' @useDynLib helloextendr, .registration = TRUE
NULL

#' @export
hello_extendr_error <- function(fail_type) .Call(wrap__hello_extendr_error, fail_type)

hello_string_error <- function(fail_type) .Call(wrap__hello_string_error, fail_type)

#' @export
hello_robj_error <- function(fail_type) .Call(wrap__hello_robj_error, fail_type)

